Repository woowa-techcamp-2021/cashbook-2, pull requests merged in 2021-07, with the labels that each got.

#2 [#002] Issue Template 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#3 feat/client-setting: 클라이언트 webpack 세팅
  .gitignore
  client/index.js
  client/package-lock.json
  client/package.json
  client/webpack.config.js
  public/dist/index.js
Labels: enhancement

#4 [#000] esLint 와 Prettier설정 끝냈습니다.
  .eslintrc.json
  .gitignore
  .prettierrc.json
  client/index.js
  package-lock.json
  package.json
Labels: enhancement

#5 [#000] fix - template ( PR, Feature ) 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#22 [#021] feat/mvc mock up
  .gitignore
  client/components/.keep
  client/index.js
  client/lib/.keep
  client/lib/Component.js
  client/lib/Controller.js
  client/lib/Model.js
  client/lib/TestPage.js
  client/pages/.keep
  client/util/.keep
  public/dist/index.js
Labels: Framework, enhancement, frontend

#28 [#027] feat / read me 작성
  README.md
Labels: documentation

#29 [#000] feat / common styles 추가(size, color)
  client/pages/color.scss
  client/pages/size.scss
Labels: frontend

#31 [#021] feat / component framework 개발
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  client/components/.keep
  client/components/Test/Test.scss
  client/components/Test/TestComponent.js
  client/components/Test/TestPage.js
  client/index.js
  client/lib/.keep
  client/lib/Component.js
  client/package-lock.json
  client/package.json
  client/util/.keep
  client/util/util.js
  public/.DS_Store
  public/dist/index.html
Labels: Framework, additional, frontend

#32 [#007] feat / header Mock Up 및 이동시 애니메이션 추가
  .DS_Store
  client/.DS_Store
  client/asset/.DS_Store
  client/asset/left-arrow.svg
  client/asset/right-arrow.svg
  client/components/Button/Button.js
  client/components/Button/Button.scss
  client/components/Header/Header.js
  client/components/Header/Header.scss
  client/components/Test/Test.scss
  client/components/Test/TestComponent.js
  client/components/Test/TestPage.js
  client/index.js
  client/lib/Component.js
  client/package-lock.json
  client/package.json
  client/pages/.keep
  client/pages/Layout/Layout.js
  client/pages/reset.scss
  client/pages/size.scss
  client/util/constant.js
  client/webpack.config.js
  public/dist/index.html
  public/index.html
Labels: enhancement, frontend

#34 [#00] 서버 histories 관련 api 개발 완료
  client/lib/router.js
  server/db/init.js
  server/db/models/category.js
  server/db/models/history.js
  server/db/models/payment.js
  server/routes/history.js
  server/routes/payment.js
  server/utils/routes/index.js
Labels: Framework, backend

#33 [#014] feat / modal 개발 완료
  client/components/Button/Button.js
  client/components/Button/Button.scss
  client/components/Header/Header.js
  client/components/Header/Header.scss
  client/components/Modal/Modal.js
  client/components/Modal/Modal.scss
  client/index.js
  client/lib/Component.js
  client/package-lock.json
  client/package.json
  client/pages/Test/Test.scss
  client/pages/Test/TestPage.js
  client/pages/color.scss
  client/pages/reset.scss
  client/pages/size.scss
  client/util/constant.js
  client/webpack.config.js
  public/index.html
Labels: enhancement, frontend

#36 [#26] github OAuth 기능 구현
  server/.env.sample
  server/package-lock.json
  server/package.json
  server/routes/users.js
Labels: additional, backend, enhancement

#37 [#011-016] feat / main mockup 완료
  client/asset/.DS_Store
  client/asset/down.svg
  client/asset/saveChecked.png
  client/asset/saveEmpty.png
  client/asset/toggleOff.png
  client/asset/toggleOn.png
  client/components/Header/Header.js
  client/components/HistoryContainer/History.js
  client/components/HistoryContainer/History.scss
  client/components/HistoryContainer/HistoryContainer.js
  client/components/InfoBar/InfoBar.js
  client/components/InfoBar/InfoBar.scss
  client/components/InputBar/InputBar.js
  client/components/InputBar/InputBar.scss
  client/index.js
  client/lib/Component.js
  client/lib/TestPage.js
  client/lib/router.js
  client/pages/Main/Main.js
  client/pages/Main/Main.scss
  client/pages/global.scss
  client/pages/reset.scss
  client/pages/size.scss
  client/util/tempHistory.js
  client/util/util.js
Labels: enhancement, frontend

#38 [#18] feat / Calendar component mockup 완료
  client/components/Calendar/Calendar.js
  client/components/Calendar/Calendar.scss
  client/components/Table/Table.js
  client/components/Table/Table.scss
  client/pages/size.scss
  client/util/util.js
Labels: enhancement, frontend

#39 [#018] feat / calendar Page 로 구현
  client/components/Calendar/Calendar.js
  client/components/Calendar/Calendar.scss
  client/components/Table/Table.js
  client/index.js
  client/lib/router.js
  client/pages/Calendar/CalendarPage.js
  client/pages/Calendar/CalendarPage.scss
Labels: enhancement, frontend

#40 [#00] feat / router로 탭에 따라 각 페이지 렌더링 구현
  client/components/Calendar/Calendar.js
  client/components/Header/Header.js
  client/components/Table/Table.js
  client/index.js
  client/lib/router.js
Labels: enhancement, frontend

#41 fix/src error
  client/components/InputBar/InputBar.js
Labels: bug
