Repository woowa-techcamp-2021/cashbook-2, pull requests merged in 2021-08, with the labels that each got.

#44 [#00] fix / Router 렌더링 구조 변경, minor bug fix
  client/components/Button/Button.js
  client/components/Header/Header.js
  client/components/InputBar/InputBar.scss
  client/index.js
  client/lib/Component.js
  client/pages/Calendar/CalendarPage.js
  client/pages/Main/Main.js
  server/routes/history.js
  server/routes/payment.js
  server/routes/users.js
  server/utils/constant.js
Labels: frontend

#45 [#021] feature / header model state
  .DS_Store
  .eslintrc.json
  client/.DS_Store
  client/components/Calendar/Calendar.js
  client/components/Header/Header.js
  client/components/InputBar/InputBar.js
  client/index.js
  client/lib/Component.js
  client/lib/Controller.js
  client/lib/Model.js
  client/lib/router.js
  client/util/util.js
  devServer.js
  package-lock.json
  package.json
Labels: Framework, frontend

#48 [#0] feat / add favicon and title.
  public/.DS_Store
  public/favicon.ico
  public/index.html
Labels: additional, frontend

#46 [#11] fix / input bar
  client/components/Button/Button.scss
  client/components/Calendar/Calendar.scss
  client/components/DripdownList/DropdownList.js
  client/components/DripdownList/dropdownList.scss
  client/components/Dropdown/Dropdown.js
  client/components/Dropdown/dropdown.scss
  client/components/HistoryContainer/History.scss
  client/components/InfoBar/InfoBar.scss
  client/components/InputBar/InputBar.js
  client/components/InputBar/InputBar.scss
  client/pages/Main/Main.js
  client/util/constant.js
  client/util/util.js
  package.json
Labels: bug, enhancement, frontend

#50 [#20] feature / add chart page
  client/index.js
  client/pages/Chart/ChartPage.js
  client/pages/Chart/chart.scss
  client/pages/Main/MainPage.js
Labels: enhancement, frontend

#53 [#23] feat / line chart Mockup
  client/components/LineChart/LineChart.js
  client/components/LineChart/lineChart.scss
  client/pages/Chart/ChartPage.js
  client/util/constant.js
Labels: enhancement, frontend

#51 [#00] fix / input add button size fixed, getter setter changes
  client/components/InputBar/InputBar.js
  client/components/InputBar/InputBar.scss
  client/components/PieChart/PieChart.js
  client/components/PieChart/PieChart.scss
  client/components/Table/Table.js
  client/lib/router.js
  client/pages/Calendar/CalendarPage.js
  client/util/constant.js
  package-lock.json
Labels: bug

#52 [#20] feat / pie chart 자바스크립트로 구현
  client/components/Dropdown/Dropdown.js
  client/components/DropdownItem/DropdownItem.js
  client/components/DropdownItem/dropdownItem.scss
  client/components/InputBar/InputBar.js
  client/index.js
  client/pages/Chart/ChartPage.js
  client/pages/Chart/chart.scss
  client/pages/Main/MainPage.js
Labels: enhancement, frontend

#54 [#00] fix/server 쿼리 오작동 문제 수정
  server/app.js
  server/db/models/category.js
  server/db/models/history.js
  server/db/models/index.js
  server/db/models/payment.js
  server/db/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/history.js
  server/routes/index.js
  server/services/historyService.js
  server/services/paymentService.js
  server/utils/constant.js
  server/utils/routes/index.js
Labels: backend, bug

#55 [#00] fix/payment service의 getPaymentId에서 PaymentId를 리턴하도록 수정
  server/routes/history.js
  server/services/historyService.js
  server/services/paymentService.js
Labels: bug

#58 [#26] feat / server Github 로그인 수정 및 인증 로직 추가
  .eslintrc.json
  server/app.js
  server/db/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/history.js
  server/routes/index.js
  server/routes/payment.js
  server/routes/users.js
  server/services/history-service.js
  server/services/payment-service.js
  server/services/paymentService.js
  server/services/user-service.js
  server/utils/auth/jwt.js
  server/utils/auth/middleware.js
  server/utils/routes/index.js
Labels: backend, enhancement

#57 [#10] feat/login modal 추가.
  client/.DS_Store
  client/asset/github/.DS_Store
  client/asset/github/github1.png
  client/asset/github/github10.png
  client/asset/github/github11.png
  client/asset/github/github12.png
  client/asset/github/github13.png
  client/asset/github/github14.png
  client/asset/github/github15.png
  client/asset/github/github16.png
  client/asset/github/github17.png
  client/asset/github/github18.png
  client/asset/github/github19.png
  client/asset/github/github2.png
  client/asset/github/github20.png
  client/asset/github/github21.png
  client/asset/github/github22.png
  client/asset/github/github23.png
  client/asset/github/github24.png
  client/asset/github/github3.png
  client/asset/github/github4.png
  client/asset/github/github5.png
  client/asset/github/github6.png
  client/asset/github/github7.png
  client/asset/github/github8.png
  client/asset/github/github9.png
  client/components/Modal/LoginModal.js
  client/components/Modal/Modal.scss
  client/pages/Main/MainPage.js
  client/util/util.js
Labels: enhancement, frontend

#61 [#18] feat / calendar now day 표시.
  client/components/Calendar/Calendar.js
  client/components/Table/Table.js
  client/components/Table/Table.scss
  client/pages/Calendar/CalendarPage.js
  client/pages/Main/MainPage.js
Labels: enhancement, frontend

#63 [#00] Feat/client server data render
  client/components/Header/Header.js
  client/components/Header/headerModel.js
  client/components/HistoryContainer/History.js
  client/components/InputBar/InputBar.js
  client/components/Modal/LoginModal.js
  client/config/index.js
  client/lib/Component.js
  client/lib/Controller.js
  client/lib/api.js
  client/pages/Main/MainModel.js
  client/pages/Main/MainPage.js
  client/util/constant.js
  client/util/tempHistory.js
  client/util/util.js
  server/.env.sample
  server/app.js
  server/db/init.js
  server/db/models/index.js
  server/package.json
  server/routes/users.js
Labels: backend, frontend

#60 [#23] feat / chart assemble
  client/components/HistoryContainer/HistoryContainer.js
  client/components/LineChart/LineChart.js
  client/components/LineChart/lineChart.scss
  client/pages/Chart/ChartPage.js
  client/pages/Chart/chart.scss
  client/util/constant.js
  server/db/models/category.js
Labels: enhancement, frontend

#64 [#00] Fix / v1.2
  client/components/HistoryContainer/History.scss
  client/components/InputBar/InputBar.js
  client/components/Modal/Modal.scss
  client/package.json
  client/pages/Chart/ChartPage.js
  client/pages/Main/MainPage.js
  client/util/constant.js
  server/db/config/config.json
Labels: bug

#65 [#20] feat / pie chart refactor
  .gitignore
  client/components/Calendar/Calendar.js
  client/components/Header/Header.js
  client/components/Header/headerModel.js
  client/components/PieChart/PieChart.js
  client/components/PieChart/PieChart.scss
  client/pages/Calendar/CalendarPage.js
  server/db/config/config.json
Labels: frontend

#70 [#23] feat / chart page statistic 컴포넌트 추가 및 렌더링
  client/components/PieChart/PieChart.js
  client/components/Statistic/Statistic.js
  client/components/Statistic/Statistic.scss
  client/pages/Chart/ChartPage.js
  client/pages/Chart/chart.scss
  client/pages/Chart/chartModel.js
  client/util/constant.js
  server/services/history-service.js
Labels: enhancement, frontend

#72 [#00] feat/server 404 page create
  client/components/Calendar/Calendar.scss
  client/components/Modal/LoginModal.js
  client/config/index.js
  client/pages/Chart/chart.scss
  config/index.js
  public/404.html
  server/app.js
Labels: backend

#71 Feat/history crud
  client/components/AlertUp/Alert.scss
  client/components/AlertUp/AlertUp.js
  client/components/Calendar/Calendar.js
  client/components/Header/Header.js
  client/components/Header/Header.scss
  client/components/InputBar/InputBar.js
  client/components/Modal/LoginModal.js
  client/lib/Component.js
  client/pages/Calendar/CalendarPage.js
  client/pages/Main/MainPage.js
  client/util/constant.js
  client/util/util.js
Labels: bug, enhancement, frontend

#74 [#00] fix/main loading
  client/config/index.js
  client/pages/Main/MainModel.js
  client/pages/Main/MainPage.js
  client/pages/reset.scss
Labels: frontend, additional
